const formatMoney=value=>new Intl.NumberFormat('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value)||0);
const formatDate=value=>{if(!value)return'-';const parts=String(value).split('-');if(parts.length!==3)return String(value);const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return parts[2]+' '+(months[Number(parts[1])-1]||'')+' '+parts[0]};
function amountToWords(value){
  const below=['Zero','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'],tens=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];
  const under=n=>{if(n<20)return below[n];if(n<100)return tens[Math.floor(n/10)]+(n%10?' '+below[n%10]:'');return below[Math.floor(n/100)]+' Hundred'+(n%100?' '+under(n%100):'')};
  const n0=Math.round((Number(value)||0)*100),rupees=Math.floor(n0/100),paise=n0%100;let n=rupees;const parts=[];const crore=Math.floor(n/10000000);n%=10000000;const lakh=Math.floor(n/100000);n%=100000;const thousand=Math.floor(n/1000);n%=1000;if(crore)parts.push(under(crore)+' Crore');if(lakh)parts.push(under(lakh)+' Lakh');if(thousand)parts.push(under(thousand)+' Thousand');if(n)parts.push(under(n));return'Rupees '+(parts.join(' ')||'Zero')+(paise?' and '+under(paise)+' Paise':'')+' Only';
}
async function logoData(){try{const r=await fetch('/mainlogo.png',{cache:'force-cache'});if(!r.ok)return'';const blob=await r.blob();return await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>resolve('');reader.readAsDataURL(blob)})}catch{return''}}
function stampDateText(value){const p=String(value||'').split('-'),m=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];return p.length===3?(p[2]+' '+(m[Number(p[1])-1]||'')+' '+p[0]).trim():'DATE'}
async function paidStampData(date){
  try{
    if(document.fonts&&document.fonts.load){await Promise.allSettled([document.fonts.load('900 100px Poppins'),document.fonts.load('700 26px Poppins')]);await document.fonts.ready}
    const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=1200;const c=canvas.getContext('2d');if(!c)return'';const family='Poppins, Inter, Arial, sans-serif',blue='#1c3e96';
    c.scale(2.4,2.4);c.translate(250,250);c.rotate(-8*Math.PI/180);c.globalAlpha=.92;c.strokeStyle=blue;c.fillStyle=blue;c.lineCap='round';
    [[240,9],[226,2.5],[168,2.5]].forEach(r=>{c.beginPath();c.lineWidth=r[1];c.arc(0,0,r[0],0,Math.PI*2);c.stroke()});
    const arc=(text,radius,center,font,spacing,direction)=>{c.font=font;c.textAlign='left';c.textBaseline='middle';const chars=Array.from(text),widths=chars.map(ch=>c.measureText(ch).width),total=widths.reduce((x,y)=>x+y,0)+spacing*(chars.length-1);let cursor=-total/2;chars.forEach((ch,i)=>{const offset=cursor+widths[i]/2,angle=center+direction*offset/radius;c.save();c.translate(radius*Math.cos(angle),radius*Math.sin(angle));c.rotate(angle-center);c.fillText(ch,-widths[i]/2,0);c.restore();cursor+=widths[i]+spacing})};
    arc('MY JEE MENTOR',190,Math.PI*1.5,'800 38px '+family,4,1);arc('CONCEPT FIRST \u2022 RANK NEXT',212,Math.PI/2,'700 26px '+family,3,-1);
    c.font='700 26px '+family;c.textAlign='center';c.textBaseline='middle';c.fillText('\u2605',-200,0);c.fillText('\u2605',200,0);
    c.font='900 96px '+family;const paid='PAID',space=6,widths=Array.from(paid).map(ch=>c.measureText(ch).width);let full=widths.reduce((x,y)=>x+y,0)+space*(paid.length-1),x=-full/2;Array.from(paid).forEach((ch,i)=>{c.fillText(ch,x+widths[i]/2,-29);x+=widths[i]+space});
    c.beginPath();c.lineWidth=1.5;c.moveTo(-80,10);c.lineTo(80,10);c.stroke();c.font='700 26px '+family;c.fillText(stampDateText(date),0,51);
    c.save();c.globalCompositeOperation='destination-out';c.globalAlpha=.18;for(let i=0;i<150;i++){const a=Math.random()*Math.PI*2,r=176+Math.random()*59;c.beginPath();c.arc(Math.cos(a)*r,Math.sin(a)*r,.2+Math.random()*.45,0,Math.PI*2);c.fill()}c.restore();return canvas.toDataURL('image/png');
  }catch{return''}
}
function fitLine(d,value,x,y,width,size,minSize,style){let text=String(value||'-').trim()||'-';d.setFont('helvetica',style||'bold');d.setFontSize(size||13);while(d.getTextWidth(text)>width&&(size||13)>(minSize||9)){size=(size||13)-.5;d.setFontSize(size)}if(d.getTextWidth(text)>width){while(text.length>1&&d.getTextWidth(text.slice(0,-1)+'...')>width)text=text.slice(0,-1);text=text.slice(0,-1)+'...'}d.text(text,x,y)}
function labelText(d,text,x,y,color){d.setFont('helvetica','bold');d.setFontSize(9);d.setTextColor(...color);if(d.setCharSpace)d.setCharSpace(.3);d.text(String(text).toUpperCase(),x,y);if(d.setCharSpace)d.setCharSpace(0)}
export async function downloadReceiptPdf(record){
  const JsPdf=window.jspdf&&window.jspdf.jsPDF;if(!JsPdf)throw new Error('Receipt PDF tool is still loading. Please try Download PDF Again in a moment.');
  const d=new JsPdf({format:'a4',unit:'mm',compress:true}),navy=[20,33,61],orange=[244,119,33],label=[180,83,9],ink=[17,24,39],cream=[255,247,239],edge=[241,210,181],green=[21,128,61],red=[185,28,28];
  d.setFillColor(255,255,255);d.rect(0,0,210,297,'F');
  d.setFillColor(...navy);d.rect(0,0,210,60,'F');d.setFillColor(...orange);d.rect(0,0,3,60,'F');d.setFillColor(255,255,255);d.roundedRect(13,9,47,40,4,4,'F');
  const logo=await logoData();if(logo){try{const im=new Image();im.src=logo;await im.decode();const w=Math.min(43,40*im.width/im.height),h=w*im.height/im.width;d.addImage(logo,'PNG',15+(43-w)/2,9+(40-h)/2,w,h)}catch{}}
  d.setTextColor(255,255,255);d.setFont('helvetica','bold');d.setFontSize(19);d.text('My JEE Mentor',66,24);d.setFontSize(8.5);d.text('IIT-JEE | NEET | FOUNDATION',66,35);d.setFont('helvetica','normal');d.setFontSize(9);d.text('Concept First. Rank Next.',66,43);
  d.setFont('helvetica','bold');d.setFontSize(22);d.text('FEE RECEIPT',197,20,{align:'right'});d.setFillColor(38,54,84);d.roundedRect(126,28,71,23,3,3,'F');d.setFontSize(8.5);d.text('Receipt No: '+(record.receiptNo||'-'),132,37);d.setFont('helvetica','normal');d.setFontSize(9);d.text('Date: '+formatDate(record.date),132,45);
  d.setFillColor(...cream);d.setDrawColor(...edge);d.setLineWidth(.35);d.roundedRect(13,68,184,61,3,3,'FD');d.setFillColor(...orange);d.rect(13,71,2,55,'F');d.setDrawColor(...edge);d.line(105,68,105,129);d.line(15,88.3,197,88.3);d.line(15,108.6,197,108.6);
  const fields=[['Student Name',record.studentName],['Parent Name',record.parentName],['Phone',record.phone],['Course',record.course],['Batch',record.batch],['Fee Period',record.feePeriod]];fields.forEach((f,i)=>{const col=i%2,row=Math.floor(i/2),x=col?111:19,y=68+row*20.3;labelText(d,f[0],x,y+7,label);d.setTextColor(...ink);fitLine(d,f[1],x,y+16,79,13,9,'bold')});
  d.setFont('helvetica','bold');d.setFontSize(12);d.setTextColor(...navy);d.text('PAYMENT DETAILS',13,141);const cols=[13,80,119,154,197],top=145,hh=11,rh=18;d.setFillColor(...navy);d.roundedRect(13,top,184,hh,2,2,'F');d.rect(13,top+7,184,4,'F');d.setFont('helvetica','bold');d.setFontSize(9);d.setTextColor(255,255,255);['Description','Fee Period','Payment Mode','Amount'].forEach((v,i)=>d.text(v,i===0?cols[i]+4:(cols[i]+cols[i+1])/2,top+7.5,{align:i===0?'left':'center'}));
  d.setFillColor(255,255,255);d.setDrawColor(...edge);d.roundedRect(13,top+hh,184,rh,0,0,'FD');[cols[1],cols[2],cols[3]].forEach(x=>d.line(x,top+hh,x,top+hh+rh));d.setFont('helvetica','bold');d.setFontSize(11);d.setTextColor(...ink);fitLine(d,'Tuition Fee - '+(record.course||'-'),17,top+hh+11,60,11,9,'bold');fitLine(d,record.feePeriod,83,top+hh+11,33,11,9,'bold');fitLine(d,record.paymentMode,122,top+hh+11,29,11,9,'bold');d.setFontSize(11);d.text('INR '+formatMoney(record.amount),193,top+hh+11,{align:'right'});
  labelText(d,'Amount in Words',13,184,label);d.setFont('helvetica','bolditalic');d.setFontSize(11);d.setTextColor(...ink);d.text(d.splitTextToSize(amountToWords(record.amount),88).slice(0,3),13,194,{lineHeightFactor:1.28});
  d.setFillColor(...cream);d.setDrawColor(...edge);d.roundedRect(111,181,86,47,3,3,'FD');labelText(d,'Amount Paid',118,190,label);d.setFontSize(30);d.setTextColor(...orange);fitLine(d,'INR '+formatMoney(record.amount),118,202,72,30,21,'bold');const balance=Number(record.balanceDue)>0?red:green;d.setTextColor(...balance);fitLine(d,'Balance Due: INR '+formatMoney(record.balanceDue),118,214,73,10.5,9.5,'bold');d.setTextColor(...ink);fitLine(d,'Collected By: '+(record.collectedBy||'-'),118,224,73,10.5,9.5,'bold');
  d.setFillColor(255,255,255);d.setDrawColor(...edge);d.roundedRect(13,233,103,39,2,2,'FD');labelText(d,'Remarks',18,241,label);d.setFont('helvetica','normal');d.setFontSize(10.5);d.setTextColor(...ink);let lines=d.splitTextToSize(String(record.remarks||'-'),92);if(lines.length>4){lines=lines.slice(0,4);lines[3]=lines[3].slice(0,Math.max(1,lines[3].length-3))+'...'}d.text(lines,18,249,{lineHeightFactor:1.2});
  const stamp=await paidStampData(record.date);if(stamp){try{d.addImage(stamp,'PNG',148,231,40,40,undefined,'FAST')}catch{}}
  d.setFont('helvetica','bold');d.setFontSize(10);d.setTextColor(...ink);d.text('Authorised Signature',168,276,{align:'center'});d.setDrawColor(...orange);d.setLineWidth(.6);d.line(13,283,197,283);d.setFontSize(9);d.text('Thank you for choosing My JEE Mentor.  |  myjeementor.com',105,289,{align:'center'});d.setFont('helvetica','normal');d.setFontSize(8);d.text('This is a computer generated receipt.',105,294,{align:'center'});
  if(d.GState&&d.setGState){try{d.setGState(new d.GState({opacity:.045}));d.setFont('helvetica','bold');d.setFontSize(35);d.setTextColor(...navy);d.text('MY JEE MENTOR',105,167,{align:'center',angle:0});d.setGState(new d.GState({opacity:1}))}catch{}}
  const safe=String(record.studentName||'student').replace(/[^a-z0-9_-]+/gi,'-').slice(0,40);d.save((record.receiptNo||'MJM-Receipt')+'-'+safe+'.pdf');
}
