document.querySelectorAll('#lead-form').forEach(async form=>{try{const config=await fetch('/api/config').then(response=>response.json());if(config.turnstileSiteKey){const slot=document.createElement('div');slot.className='field full turnstile';slot.dataset.sitekey=config.turnstileSiteKey;form.querySelector('.form-status').before(slot);await new Promise(resolve=>{const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=resolve;document.head.append(script)});window.turnstile?.render(slot,{sitekey:config.turnstileSiteKey})}}catch{}});
document.addEventListener('submit',async event=>{
  const form=event.target;if(form.id!=='lead-form')return;event.preventDefault();
  const status=form.querySelector('.form-status'),data=Object.fromEntries(new FormData(form).entries()),token=form.querySelector('[name="cf-turnstile-response"]')?.value;
  if(form.querySelector('.turnstile')&&!token){status.style.display='block';status.classList.add('error');status.textContent='Complete the security check to continue.';return}
  const whatsapp=form.querySelector('[data-lead-whatsapp]');
  if(whatsapp){const labels={studentName:'Student Name',parentName:'Parent Name',email:'Email',mobile:'Mobile',whatsapp:'WhatsApp',className:'Class',exam:'Course',targetYear:'Target Year',currentCoaching:'Current Coaching',preferredSubject:'Preferred Subject',city:'City',language:'Preferred Language',message:'Message'};const lines=Object.entries(labels).filter(([key])=>data[key]?.trim()).map(([key,label])=>`${label}: ${data[key].trim()}`);whatsapp.href=`https://wa.me/917304256203?text=${encodeURIComponent(`Hi, I submitted a counselling enquiry.\n\n${lines.join('\n')}`)}`}
  status.style.display='block';status.classList.remove('error');status.textContent='Sending your enquiry…';
  try{const csrf=await fetch('/api/csrf',{credentials:'same-origin'}).then(response=>response.json());const response=await fetch('/api/leads',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','x-csrf-token':csrf.token},body:JSON.stringify({...data,turnstileToken:token||''})});const result=await response.json();if(!response.ok)throw new Error(result.message||'Please check the form fields and try again.');status.textContent='Thank you! Your enquiry was emailed to our team. You can also open WhatsApp below with your details pre-filled.';if(typeof gtag==='function')gtag('event','form_submit',{form_id:'lead-form'})}catch(error){status.classList.add('error');status.textContent=error.message==='Failed to fetch'?'Form service is unavailable. Please call or WhatsApp us.':error.message}
});
